NSCC-ITC-Winter2025-WEBD3031-700-MCa/webd3031-project-beachreport

package.json, pnpm-lock.yaml, prisma/migrations/20250307185728_add_password_reset_fields/migration.sql, prisma/schema.prisma, src/app/api/forgot-password/reset/route.ts, src/app/api/forgot-password/update/route.ts, src/app/api/forgot-password/verify-token/route.ts
=> 46 fix deploy

src/components/Header/index.tsx
=> feat: styled nav bar and logo

src/app/api/beaches/route.ts, src/components/Header/index.tsx, src/components/Header/menuData.tsx, tsconfig.json
=> feat: linked pages to nav bar

src/app/(site)/beaches/[slug]/page.tsx, src/app/(site)/beaches/[slug]/report/page.tsx, src/app/api/reports/route.ts
Closes #31 
Will add additional functionality if we have time, but would need to update the database to do so (such as radio buttons for water quality/parking situation...etc
=> feat: added beach report form and api

src/components/Footer/index.tsx
fixes #8, #17 & #19 
still needs updated links but will make another ticket for that and do it once we have all the routes good to go
=> feat: customized footer

src/components/Header/index.tsx
=> nav bar shows signOut now

src/app/api/auth/[...nextauth]/route.ts, src/app/api/auth/signin/route.ts, src/components/Header/index.tsx, src/types/next-auth.d.ts
=> feat: added nav item for dashboard that only shows up for admin users

src/app/(site)/pricing/page.tsx, src/app/api/payment/route.ts, src/components/Pricing/PricingBox.tsx, src/components/Pricing/index.tsx
=> feat: added payment page with link to stripe payment

src/app/api/auth/[...nextauth]/route.ts
=> fix: fixed deployment typescript errors

tsconfig.json
=> fix: fixed typescript errors

tsconfig.json
=> fix: ts config fixes

src/app/(site)/beaches/[slug]/page.tsx, src/app/(site)/beaches/[slug]/report/page.tsx, src/app/api/auth/[...nextauth]/route.ts, src/app/api/auth/signin/route.ts, src/app/api/user-subscription/route.ts, src/types/next-auth.d.ts
=> feat: restricted reports to be viewable by subs only

src/app/(site)/about/page.tsx, src/app/(site)/beaches/[slug]/report/page.tsx, src/app/(site)/contact/page.tsx, src/app/(site)/pricing/page.tsx, src/app/head.tsx, src/app/page.tsx
=> fix: updated site title and description

src/components/CallToAction/index.tsx, src/components/Hero/index.tsx
=> feat: implemented search functionality

package.json, pnpm-lock.yaml
=> fix: updated next version for patch

prisma/migrations/20250331135803_add_account_unique_constraint/migration.sql, prisma/migrations/20250331141544_add_account_type/migration.sql, prisma/migrations/20250331145404_update_account_oauth_fields/migration.sql, prisma/schema.prisma, src/utils/auth.ts
=> feat(auth): add Google OAuth login and support Prisma OAuth fields

package.json, pnpm-lock.yaml
=> fix: install @next-auth/prisma-adapter

pnpm-lock.yaml
=> feat: fix deployment build error

src/app/(site)/(auth)/signin/page.tsx, src/app/(site)/(auth)/signup/page.tsx, src/components/Auth/SignIn/index.tsx, src/components/Auth/SignUp/index.tsx
=> fix: removed breadcrumbs from signin/up

src/components/Footer/index.tsx
=> feat: added footer links

src/utils/auth.ts
=> feat: added username display to all signins

src/app/api/reports/route.ts
=> fix: updated hard coded userId

src/components/Header/index.tsx
=> fix: make all nav items responsive

src/components/BeachMap/index.tsx
=> feat: added links to map popups
